'use client';

import { useState } from 'react';
import Image from 'next/image';
import { handleImageGeneration } from '@/app/actions';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Sparkles, Download, Save, AlertCircle } from 'lucide-react';
import { useToast } from "@/hooks/use-toast";
import { LoadingSpinner } from './loading-spinner';

export function ImageGenerator() {
  const [prompt, setPrompt] = useState('');
  const [generatedImage, setGeneratedImage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError('');
    setGeneratedImage('');

    const result = await handleImageGeneration(prompt);

    if (result.success && result.data) {
      setGeneratedImage(result.data.imageDataUri);
    } else {
      setError(result.error || 'An unknown error occurred.');
    }
    setIsLoading(false);
  };

  const handleSave = () => {
    toast({
      title: "Feature not available",
      description: "Saving content will be implemented soon.",
    });
  };
  
  const handleDownload = () => {
    if (!generatedImage) return;
    const link = document.createElement('a');
    link.href = generatedImage;
    link.download = `gemini-studio-image-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      <form onSubmit={handleSubmit} className="space-y-4">
        <Textarea
          placeholder="e.g., A futuristic cityscape at night with flying cars, neon lights, detailed, 8k"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          rows={3}
          className="text-base"
          disabled={isLoading}
        />
        <Button type="submit" disabled={isLoading || !prompt} className="w-full sm:w-auto" variant="outline">
          {isLoading ? <LoadingSpinner className="mr-2" /> : <Sparkles className="mr-2" />}
          Generate Image
        </Button>
      </form>

      {error && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {isLoading && (
        <Card>
          <CardHeader>
            <CardTitle>Generating...</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="aspect-[3/2] w-full">
              <Skeleton className="w-full h-full" />
            </div>
          </CardContent>
        </Card>
      )}

      {generatedImage && (
        <Card className="overflow-hidden">
          <CardHeader>
            <CardTitle>Generated Image</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="aspect-[3/2] w-full relative rounded-md overflow-hidden">
              <Image 
                src={generatedImage} 
                alt="Generated by AI" 
                fill
                className="object-contain"
                data-ai-hint="generated image"
              />
            </div>
          </CardContent>
          <CardFooter className="gap-2">
            <Button onClick={handleDownload} variant="secondary">
              <Download className="mr-2" /> Download
            </Button>
            <Button onClick={handleSave} variant="secondary">
              <Save className="mr-2" /> Save to Library
            </Button>
          </CardFooter>
        </Card>
      )}
    </div>
  );
}
